name: deploy github pages

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    name: Upload github pages
    runs-on: ubuntu-latest
    env:
      REACT_APP_ALLOW_REMOTE: true
      REACT_APP_ORIGINAL_HOSTED_SITE: true
      REACT_APP_SHORT_DOMAIN: ipa.wdurand.com
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.x"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn.cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable

      - run: yarn test
      - run: yarn build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: ipa.winstondurand.com
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com
