name: Lint

on:
  - push
  - pull_request

jobs:
  deploy:
    name: Lint files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: "14.x"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: .yarn/cache
          key: ${{ runner.os }}-yarn.cache-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: yarn install --immutable

      # require all lints to pass without warnings and files to be formatted well
      - run: yarn lint-ci
      - run: yarn prettier --check ./src
